# Generated by Django 4.2.30 on 2026-10-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITLabEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(choices=[('Server Room', 'Central Server Room'), ('AI & DS Lab', 'AI & Data Science Lab'), ('Network Lab', 'Networking & Security Lab'), ('Software Lab', 'Software Engineering Lab'), ('Cloud Lab', 'Cloud Computing Lab')], max_length=50)),
                ('device_type', models.CharField(max_length=100)),
                ('units_kwh', models.FloatField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
